### ISSUE TITLE
Q:Expand some row

### ISSUE THREAD

**Issue by rb0071** [sjthn/RecyclerViewDemo#3]
Can I expand some header when recyclerView set adapter success?

**Comment by sjthn** [comment]
what do you mean by set adapter success? If you mean after adapter has been set, then yes you can do that.

**Comment by rb0071** [comment]
After adapter has been set and recyclerview show data, Can I set automatic expand some header? Could you give us an example?

**Comment by sjthn** [comment]
Unfortunately I don't have an example. If I can come up with an idea quickly, whatever data you are passing, add a flag which tells whether to expand the a header or not. That way based on that flag you can show the header.

**Comment by sjthn** [comment]
Hey I am closing this 🙂
